[package]
name = "tokio-xmpp"
version = "0.1.0"
authors = ["Astro <astro@spaceboyz.net>"]

[dependencies]
futures = "*"
tokio-core = "*"
tokio-io = "*"
bytes = "*"
RustyXML = "*"
native-tls = "*"
tokio-tls = "*"
sasl = "*"
rustc-serialize = "*"
jid = "*"
