[package]
name = "tokio-xmpp"
version = "0.1.0"
authors = ["Astro <astro@spaceboyz.net>"]

[dependencies]
futures = "*"
tokio-core = "0.1.7"
tokio-io = "*"
bytes = "0.4.4"
xml5ever = "*"
tendril = "*"
minidom = "0.8.0"
native-tls = "*"
tokio-tls = "*"
sasl = "*"
rustc-serialize = "*"
jid = { version = "0.5.0", features = ["minidom"] }
domain = "0.2.1"
xmpp-parsers = "0.10.0"
idna = "*"
try_from = "0.2.2"
sha-1 = "0.7.0"
quick-xml = "*"
